#!/bin/bash

# ASCII Art
ascii_art="

███████╗ █████╗      ██╗   ██╗██╗███████╗███████╗██████╗ 
██╔════╝██╔══██╗     ██║   ██║██║██╔════╝██╔════╝██╔══██╗
█████╗  ███████║     ██║   ██║██║█████╗  █████╗  ██████╔╝
██╔══╝  ██╔══██║     ╚██╗ ██╔╝██║██╔══╝  ██╔══╝  ██╔═══╝ 
██║     ██║  ██║██╗   ╚████╔╝ ██║███████╗███████╗██║     
╚═╝     ╚═╝  ╚═╝╚═╝    ╚═══╝  ╚═╝╚══════╝╚══════╝╚═╝     

                                                       
                                                       
                             
                             
                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Clear the screen
clear
# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"


echo "* Installing Dependencies"

# Update package list and install dependencies
sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

echo_message "* Installed Dependencies"

echo_message "* Installing Files"

# Create directory, clone repository, and install files

git clone https://github.com/dragonlabsdev/panel-v1.0.0.git && mv panel-v1.0.0 panel && cd panel && npm install && npm run seed && npm run createUser && node .

echo_message "* Installed Files"

echo_message "* Starting Panel"



echo "* Panel Installed and Started on Port 3000'
                             
                             
                                 
"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# Clear the screen
clear
# Check if the script is run as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root.${NC}"
  exit 1
fi

echo -e "${CYAN}$ascii_art${NC}"


echo "* Installing Dependencies"

# Update package list and install dependencies
sudo apt update
sudo apt install -y curl software-properties-common
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install nodejs -y 
sudo apt install git -y

echo_message "* Installed Dependencies"

echo_message "* Installing Files"

# Create directory, clone repository, and install files

git clone https://github.com/dragonlabsdev/draco-daemon && mv draco-daemon node && cd node && npm install && cd node


echo "* paste your configure"

echo "* node ."
